[project]
name = "mcp-fantasy-draft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.13.1",
    "python-dotenv>=1.1.1",
    "yahoo-fantasy-api>=2.12.0",
    "yahoo-oauth>=2.1.1",
]
